#!/bin/bash
# Generate src/pve_hw_build_info.js from VERSION + git metadata.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/src/pve_hw_build_info.js}"
VER="$(tr -d '[:space:]' < "$ROOT/VERSION")"
GITHUB="https://github.com/mrkvka/proxmox-cpu-dashboard"
COMMIT_FULL="$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo "")"
COMMIT="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")"
BRANCH="$(git -C "$ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")"
STAMP="$(date -Iseconds)"

cat > "$OUT" << EOF
/* Auto-generated by scripts/gen-build-info.sh — do not edit */
(function() {
    window.PVECPUDash = window.PVECPUDash || {};
    PVECPUDash.BUILD_INFO = {
        repository: "${GITHUB}",
        releases: "${GITHUB}/releases",
        uiVersion: "${VER}",
        commit: "${COMMIT}",
        commitFull: "${COMMIT_FULL}",
        branch: "${BRANCH}",
        installedAt: "${STAMP}"
    };
})();
EOF
echo "Generated $OUT (${VER} @ ${COMMIT})"
